# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4e37a0ec935083052b2b5458d40ff76bcbf3cab68ffe4472e3e519318be1cf2cf1b3c25046e102619dad9dc4e83acb11db135143cde0e1fbbc3aebc6788b8d4

test:
  secret_key_base: a07d1a689ffd9bf15a58cf42f28f2369666a225a1f7c9492ee29c8ff87928d61d73205172c6843e6c2348fe492c2a540b730b3a43a1af51709ea504c4ff97b52

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
